name: download pics from bing

on: 
  workflow_dispatch:  # manually dispatch
    inputs:
      delays:
        description: '(Optional)Delayed time'
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v1
        with: 
          python-version: 3.x
      
      - name: install Request
        run: pip install requests
        
      
      - name: commit and push
        env: 
          EMAIL: ${{ secrets.email }}
          USERNAME: ${{ secrets.usernami }}
        run: python main.py
          
      
      - name: push
        uses: ad-m/github-push-action@master
        with: 
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: "main"
