name: download pics from bing

on: 
  workflow_dispatch:  # manually dispatch
    inputs:
      delays:
        description: '(Optional)Delayed time'
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: list direction
        run: ls
      
   
