name: download pics from bing

on: 
  workflow_dispatch:  # manually dispatch
    inputs:
      delays:
        description: '(Optional)Delayed time'
        required: false
jobs:
  build:
   - name: checkout code
     uses: actions/chechout@v2
   
   - name: list direction
     run: ls
